fastq_menifest: /home/hsher/projects/oligoCLIP/config/fastq_csv/singleplex_katie_igg.csv

barcode: /projects/ps-yeolab5/hsher/Katie_ABC_IgG_barcode.csv


ADAPTOR_PATH: /projects/ps-yeolab4/software/eclip/0.7.0/examples/inputs
adaptor: InvRiL19

# Resources
CHROM_SIZES: /projects/ps-yeolab3/eboyle/resources/hg38.chrom.sizes
STAR_DIR: /projects/ps-yeolab4/software/eclip/0.7.0/examples/inputs/star_2_7_gencode29_sjdb
STAR_REP: /projects/ps-yeolab4/software/eclip/0.7.0/examples/inputs/star_2_7_homo_sapiens_repbase_fixed_v2
STAR_DROS: /projects/ps-yeolab3/bay001/annotations/dm6/star_2_7_6a_release6_sjdb


PYTHON3_PATH: /home/hsher/miniconda3/bin/python # TODO: containerize
TOOL_PATH: /home/hsher/projects/oligoCLIP

umi_pattern: XXXXXNNNNN