# Basic settings
COMMENT: This is testing different controls
MANIFEST: /home/hsher/projects/oligoCLIP/config/fastq_csv/katie_pe_iteration7.csv
barcode_csv: /home/hsher/projects/oligoCLIP/config/barcode_csv/iter7.csv # reverse complemented sequence.
WORKDIR: /home/hsher/scratch/oligo_PE_iter7
AS_INPUT:  
- ctrlBead
- ctrlSpike
- ctrlSpikeSLBP
- ctrlSpikeRBFOX2
# this must be one of the rows in barcode_csv
RBP_TO_RUN_MOTIF:
- 2plexRBFOX2
- 1plexRBFOX2

run_clipper: False
run_skipper: True
run_comparison: False
debug: True

external_bam:
  K562_totalRNAseq: /home/hsher/seqdata/20230401_charl_encode_totalrnaseq/output/bams/ENCODE_K562_totalRNAseq.Aligned.sortedByCoord.out.bam

# dependency
QC_TOOLS_PATH: /home/hsher/projects/QC_tools
SCRIPT_PATH: /home/hsher/projects/oligoCLIP/scripts/
MAKE_TRACK: /home/hsher/projects/make_tracks/Snake_CLIP_track.py

# Skipper dependencies
JAVA_PATH: /projects/ps-yeolab3/eboyle/software/jdk-18.0.1.1/bin/java
UMICOLLAPSE_PATH: /projects/ps-yeolab3/eboyle/software/UMICollapse/umicollapse.jar
R_EXE: /projects/ps-yeolab4/software/R-4.1.2/bin/Rscript

# preprocessing options
adaptor_fwd: AGATCGGAAGAGCACACGTC
adaptor_rev: AGATCGGAAGAGCGTCGTGT
tile_length: 10
QUALITY_CUTOFF: 15
error_rate: 0.2
umi_length: 10
STAR_DIR: /projects/ps-yeolab3/bay001/annotations/GRCh38/star_2_7_gencode40_sjdb

# skipper annotations
PARTITION: /projects/ps-yeolab4/software/skipper/1.0.0/bin/skipper/annotations/gencode.v38.annotation.k562_totalrna.gt1.tiled_partition.bed.gz
FEATURE_ANNOTATIONS: /projects/ps-yeolab4/software/skipper/1.0.0/bin/skipper/annotations/gencode.v38.annotation.k562_totalrna.gt1.tiled_partition.features.tsv.gz
ACCESSION_RANKINGS: /projects/ps-yeolab3/eboyle/encode/pipeline/01_20211115/input/accession_type_ranking.txt
REPEAT_TABLE: /projects/ps-yeolab3/eboyle/encode/pipeline/05_20220720/repeatmasker.grch38.tsv.gz


# other annotations
CHROM_SIZES: /projects/ps-yeolab3/bay001/annotations/GRCh38/GRCh38_no_alt_analysis_set_GCA_000001405.15.chrom.sizes
GENOMEFA: /projects/ps-yeolab3/bay001/annotations/GRCh38/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta

# Single-end: enter 1. Paired-end: enter read (1 or 2) corresponding to crosslink site
INFORMATIVE_READ: 1

# CLIPper
SPECIES: GRCh38v35noalt
DATADIR: /home/hsher/scratch/clipper/clipper/data
GTF: /home/hsher/gencode_coords/gencode.v35.gtf.db
ANNOTATOR_SPECIES: GRCh38

#OmniCLIP
GFF_file: /home/hsher/gencode_coords/gencode.v38.primary_assembly.annotation.gff3
DB_FILE: /home/hsher/scratch/gencode.v38.k562.ominclip.db
GENOME_dir: /home/hsher/scratch/GRCh38.primary/

