MANIFEST: /home/hsher/projects/oligoCLIP/config/fastq_csv/katie_pe_iteration3.csv
WORKDIR: /home/hsher/scratch/oligo_PE_iter3_multimap
adaptor_fwd: AGATCGGAAGAGCACACGTC
adaptor_rev: AGATCGGAAGAGCGTCGTGT
tile_length: 10
QUALITY_CUTOFF: 15
error_rate: 0.2

umi_length: 10

barcode_csv: /home/hsher/projects/oligoCLIP/config/barcode_csv/katie_pe_iter3.csv # reverse complemented sequence.

STAR_DIR: /projects/ps-yeolab5/hsher/Tao_circSTAMP/star_2_7_gencode35

QC_TOOLS_PATH: /home/hsher/projects/QC_tools

JAVA_PATH: /projects/ps-yeolab3/eboyle/software/jdk-18.0.1.1/bin/java
UMICOLLAPSE_PATH: /projects/ps-yeolab3/eboyle/software/UMICollapse/umicollapse.jar

# region caller: Cell type specific annotations!
PARTITION: /projects/ps-yeolab4/software/skipper/1.0.0/bin/skipper/annotations/gencode.v38.annotation.k562_totalrna.gt1.tiled_partition.bed.gz
FEATURE_ANNOTATIONS: /projects/ps-yeolab4/software/skipper/1.0.0/bin/skipper/annotations/gencode.v38.annotation.k562_totalrna.gt1.tiled_partition.features.tsv.gz
ACCESSION_RANKINGS: /projects/ps-yeolab3/eboyle/encode/pipeline/01_20211115/input/accession_type_ranking.txt
CHROM_SIZES: /home/hsher/gencode_coords/GRCh38.primary_assembly.chrom.sizes
GENOMEFA: /home/hsher/gencode_coords/GRCh38.primary_assembly.genome.fa
AS_INPUT: IgG_Rb # this must be one of the rows in barcode_csv
R_EXE: /projects/ps-yeolab4/software/R-4.1.2/bin/Rscript

SCRIPT_PATH: /home/hsher/projects/oligoCLIP/scripts/

# REPEATS
REPEAT_TABLE: /projects/ps-yeolab3/eboyle/encode/pipeline/05_20220720/repeatmasker.grch38.tsv.gz

# 
MAKE_TRACK: /home/hsher/projects/make_tracks/Snake_CLIP_track.py
trackhub_genome: GRCh38

# Single-end: enter 1. Paired-end: enter read (1 or 2) corresponding to crosslink site
INFORMATIVE_READ: 1

RBP_TO_RUN_MOTIF:
- RBFOX2
- PUM2
- TIAL1
- PRPF8
- QKI
- TAF2